<!doctype html>
<html lang="en">
<head>
  <title>Reference clones at International HPV Reference Center</title>

  <meta charset="utf-8" http-equiv="Cache-control" content="no-cache">
  <meta name="description" content="List of HPV reference clones at the International HPV Reference Center.">
  <meta name="keywords" content="HPV, Novel types, Reference center">
  <meta charset="utf-8" http-equiv="Cache-control" content="public">
    <link rel="stylesheet" href="./css/styles.css">
    <!--     
         <script src="../js/google_analytics.js"></script> 
    -->
    <script src="./js/resize.js"></script>
</head>

<body>
 <div class="display_part" id="display_part_id">
     
   <div class="master_header">
     <div class="top_menu">
       <ul>
         <li id="top_menu_contacts"> <a href="about_us.html" >Contact</a> </li>
         <li id="top_menu_sitemap"> <a href="#" >Sitemap</a> </li>
         <li id="top_menu_abwe"> <a href="about_this_webpage.html" >About this website</a> </li>
       </ul>
     </div>

      <p id="top_header_name">
         International Human Papillomavirus Reference Center
      </p> 
      <a href="http://www.ki.se" id="img_KI_logo" target="_blank"><img src="./image/KI_logo.png" alt="KI logo" > </a>
      <a href="http://www.hpvcenter.se" > <img id="img_HPVref_logo" src="./image/HPV_logo.png" alt="HPV Reference Center logo" > </a>

     <div id="globalNav" >
         
       <ul>
         <li id="home" > <a href="http://hpvcenter.se/index.php" >Home</a> </li>
         <li id="refclone_li"> <a href="http://hpvcenter.se/refclones.html" >Reference clones</a> </li>
         <li id="Proficiency_Panels"> <a href="http://hpvcenter.se/Proficiency_Panels.html" >Proficiency Panels</a> </li>
         <li id="Services.html"> <a href="http://hpvcenter.se/Services.html" >Services</a> </li>
         <li id="working_groups"> <a href="http://hpvcenter.se/publications.html" >Publications</a> </li>
         <li id="news_events"> <a href="http://hpvcenter.se/news_events.html" >News & Events</a> </li>
         <li id="meetings_and_reports"> <a href="http://hpvcenter.se/meetings_and_reports.html" >Meetings & Reports</a> </li>
         <li id="useful_links"> <a href="http://hpvcenter.se/html/useful_links.html" >Links</a> </li>
       </ul>

     </div>

    <div class="topbar">
        International Human Papillomavirus Reference Center
    </div>     
   </div>

   <div class="display_with_sibar_logos">
    


